#!/bin/sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

set -e

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

APP_HOME=$(cd "${0%/*}" && pwd -P)

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -z "${ANDROID_SDK_ROOT:-}" ] && [ -d "${HOME}/Android/sdk" ]; then
  ANDROID_SDK_ROOT="${HOME}/Android/sdk"
  export ANDROID_SDK_ROOT
fi
if [ -z "${ANDROID_HOME:-}" ] && [ -n "${ANDROID_SDK_ROOT:-}" ]; then
  ANDROID_HOME="${ANDROID_SDK_ROOT}"
  export ANDROID_HOME
fi

JAVA_HOME=${JAVA_HOME:-}
if [ -z "$JAVA_HOME" ]; then
  JAVA_CMD="java"
else
  JAVA_CMD="$JAVA_HOME/bin/java"
fi

exec "$JAVA_CMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  -Dorg.gradle.appname="$APP_BASE_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
